name: Deploy Frontend
on:
  push:
    branches:
      - main  # Roda em push na main (após update de dados)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar arquivos de dados (Debug)
        run: |
          ls -la data/ || echo "Pasta data/ não existe!"
          cat data/estatisticas.json || echo "estatisticas.json vazio ou ausente"
          cat data/mapa-ocorrencias.json || echo "mapa-ocorrencias.json vazio ou ausente"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4